---
title: Go Tech Foundation
author: chrisconnellydotdev inc
email: me@chrisconnelly.dev
description: ubuild-jekyll is a Jekyll theme desgined to work with Forestry's Blocks
  feature. This theme provides a set of page-level components and a pre-configured
  Forestry Blocks UI that will empower content editors to construct their own webpages.
baseurl: "/ubuild-jekyll"
url: https://kind-minsky-569cd6.netlify.app
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
